### ISSUE TITLE
关于命令的讨论

### ISSUE THREAD

**Issue by putianyi889** [T0nyX1ang/tikz-minesweeper#1]
|字符|行为|是否按下|是否已实现|备注|
|:-:|:-|:-:|:-:|:-:|
|0|数字0|1|✔️||
|1|数字1|1|✔️||
|2|数字2|1|✔️||
|3|数字3|1|✔️||
|4|数字4|1|✔️||
|5|数字5|1|✔️||
|6|数字6|1|✔️||
|7|数字7|1|✔️||
|8|数字8|1|✔️||
|b|blue|0|✔️||
|c|cyan|0|✔️||
|e|misflag|0|✔️||
|f|flag|0|✔️||
|g|green|0|✔️||
|m|mine|1|✔️||
|n|blastedmine|1|✔️||
|o|orange|0|✔️||
|r|red|0|✔️||
|s|shade|?|❌||
|v|violet|0|✔️||
|y|yellow|0|✔️||
|-|空|0|✔️||
|?|mark|0|✔️|可自动实现|

**Comment by putianyi889** [comment]
@T0nyX1ang 可以把每个命令的效果截图放到表里吗

**Comment by putianyi889** [comment]
![( C{)}7N79E%% 5RLHRK` F](https://user-images.githubusercontent.com/44583944/149671313-61eb7379-c3d4-4a40-b6b3-43aa31f5944d.png)

**Comment by T0nyX1ang** [comment]
确实可以删

**Comment by T0nyX1ang** [comment]
20221104 update: blasted mine

**Comment by T0nyX1ang** [comment]
This issue is closed now, and further discussion has been moved to Discussion Part.
