### ISSUE TITLE
[Bug] board/row/col 传入参数未进行验证

### ISSUE THREAD

**Issue by T0nyX1ang** [T0nyX1ang/tikz-minesweeper#18]
- board/row/col 目前仅验证了传入参数（行、列）是否为整数的情况，如果使用负数传入参数，绘制图像会不正常，因此需要构造一个参数校验器出来

**Comment by putianyi889** [comment]
问题不大吧，正常需求可以满足，同时也允许一些奇怪的操作

**Comment by T0nyX1ang** [comment]
考虑到 @putianyi889 的意见，或许下个版本就把验证删了，因此该issue重新开启
