### ISSUE TITLE
滤镜

### ISSUE THREAD

**Issue by putianyi889** [T0nyX1ang/tikz-minesweeper#5]
从绘图角度考虑，每个格子绘制时需要考虑很多独立的条件。
- 格子是按下还是弹起？按下则中心为`(8.5,-8.5)`，弹起则中心为`(8,-8)`
- 格子的内容是什么？
- 格子是否要上色？

显然单字符命令无法处理这么多复杂的条件，所以必须通过滤镜解决。

- [ ] 按下/弹起滤镜。因为覆盖关系，这个滤镜必须在填充内容之前添加。
- [x] 上色的滤镜。已经通过`\colorcell`解决了（https://github.com/T0nyX1ang/tikz-minesweeper/commit/0c6344da49793784629e9f7f12034666f20521c2 ）

**Comment by T0nyX1ang** [comment]
我个人对滤镜的考虑：化为两个基本命令: \row 和 \filter
+ \row 只完成一行方格的绘制 （可能会考虑加个 \col 命令, 用于一列方格绘制）
+ \filter 接受三个参数, 第一个参数指明滤镜名, 第二个参数指明方格的状态, 第三个参数指明绘制区间，第三个参数可以把妖鱼的\colorcell命令里面的思路做成一个小的解析器，前两个参数还可以继续讨论

**Comment by putianyi889** [comment]
按下/弹起滤镜因为会影响后续填充内容的操作，所以可以考虑用环境而不用单独的命令。类似于tikz的scope，所有环境内的绘制操作都受滤镜影响

**Comment by T0nyX1ang** [comment]
Marked with "wontfix" now.
