### ISSUE TITLE
优化border命令

### ISSUE THREAD

**Issue by T0nyX1ang** [T0nyX1ang/tikz-minesweeper#7]
为了接口统一，想把\trborder等命令中的长度参数移除，全部在\board中通过scope移动。

考虑改成\border{xx}的形式也可以。

如果没意见可能最近会先更新这个。

**Comment by putianyi889** [comment]
目前的四条边界需要长度，四个角不需要长度。`\border{xx}`是指类似于`\border{tr}`吗

**Comment by T0nyX1ang** [comment]
对

**Comment by T0nyX1ang** [comment]
改好了border指令：
https://github.com/T0nyX1ang/tikz-minesweeper/commit/309b4b7db0024a02254dc83d00f4e82f7b9655c0

@putianyi889 看一下这个更新怎样，谢了

**Comment by putianyi889** [comment]
大写带包围，小写不带包围？

**Comment by T0nyX1ang** [comment]
确实，不过我刚刚又想了一个代码量更少一点的写法，应该能把border和board/tlboard/tboard/lboard都给统一起来

预计操作：
\board[tTL]{3}{5} = \tlboard{3}{5}
\board[tTLlB]{3}{5} = \lboard{3}{5}

**Comment by T0nyX1ang** [comment]
效果图：
![TUC2K}$_V}~B$GJ3UOM3A_B](https://user-images.githubusercontent.com/33901373/150653577-c4af7040-97df-4204-a16c-e75d8aa172e2.png)
![V9}XFB8UVVXK R2LUBPEPMK](https://user-images.githubusercontent.com/33901373/150653583-a960379b-12f4-45bb-94a1-829ddc0cdbcb.png)

**Comment by putianyi889** [comment]
会有需要相邻两边但是不需要夹角的情况吗

**Comment by T0nyX1ang** [comment]
不会吧，但是这样写貌似并不麻烦，而且也不是四条命令，只是一条命令加可选参数

**Comment by putianyi889** [comment]
图中的后三例应用场景都不少
1. 角的命令不好记
2. 角的加入使得命令长度大大增加，而且角属于冗余信息，不利于可读性
3. 大小写反复切换使得输入命令时间进一步翻倍。大小写交错进一步增加阅读难度

**Comment by T0nyX1ang** [comment]
想了一下，自动检测拐角的功能可以有，这样可以移除这些拐角指令

**Comment by putianyi889** [comment]
可以加个取反符号吗，例如
`\board[tlr]=\board[`b]`

**Comment by T0nyX1ang** [comment]
> 可以加个取反符号吗，例如
> `\board[tlr]=\board[-b]`

貌似可行
